jobs:
  terraform:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    # ... your existing terraform steps ...

  deploy-keda:
    name: 'Deploy KEDA'
    runs-on: ubuntu-latest
    needs: terraform
    steps:
      - uses: actions/checkout@v4
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
          install_components: 'gke-gcloud-auth-plugin'
      - name: Get Cluster Credentials
        run: |
          gcloud container clusters get-credentials my-gke-cluster \
            --zone ${{ env.GCP_ZONE }} \
            --project ${{ env.GCP_PROJECT_ID }}
      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: '3.13.0'
      - name: Create Namespace
        run: |
          kubectl get ns k8-universe-project || kubectl create ns k8-universe-project
      - name: Install KEDA
        run: |
          helm repo add kedacore https://kedacore.github.io/charts
          helm repo update
          helm install keda kedacore/keda \
            --namespace k8-universe-project \
            --version 2.14.0 \
            --set resources.operator.limits.cpu=500m \
            --set resources.operator.limits.memory=512Mi \
            --set resources.operator.requests.cpu=100m \
            --set resources.operator.requests.memory=256Mi \
            --wait \
            --timeout 5m
      - name: Wait for KEDA CRDs
        run: |
          for crd in scaledobjects.keda.sh scaledjobs.keda.sh triggerauthentications.keda.sh clustertriggerauthentications.keda.sh cloudeventsources.eventing.keda.sh; do
            kubectl wait --for=condition=established crd/$crd --timeout=120s
          done

  deploy-hpa:
    name: 'Deploy Horizontal Pod Autoscaler'
    runs-on: ubuntu-latest
    needs: deploy-keda
    steps:
      - uses: actions/checkout@v4
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
          install_components: 'gke-gcloud-auth-plugin'
      - name: Get Cluster Credentials
        run: |
          gcloud container clusters get-credentials my-gke-cluster \
            --zone ${{ env.GCP_ZONE }} \
            --project ${{ env.GCP_PROJECT_ID }}
      - name: Apply HPA Manifests
        run: |
          kubectl apply -f manifests/Namespace.yaml --namespace=k8-universe-project
          kubectl apply -f manifests/Service.yaml  --namespace=k8-universe-project
          kubectl apply -f manifests/DeploymentWithHPA.yaml --namespace=k8-universe-project
      - name: Verify ScaledObjects
        run: kubectl get scaledobject -n k8-universe-project